unbind r
bind r source-file ~/.tmux.conf; display "Config reloaded!"

set -g mouse on
bind-key M-h select-pane -L
bind-key M-j select-pane -D
bind-key M-k select-pane -U
bind-key M-l select-pane -R

unbind C-b
set-option -g prefix M-a
bind-key M-a send-prefix

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

set-option -g status-position top

set -g status-style "bg=#e46400,fg=#FDFBD4,bold"
